### ISSUE TITLE
[Nfdi4Plants.Fornax] Author yaml structure

### ISSUE THREAD

**Issue by Freymaurer** [nfdi4plants/web-components#25]
So I am currently refining the yaml input while also working on #23  and #22. As already used in some knowledgebase documents, I think it's a nice idea to add github and/or orcid for authors, but now the question is how to manage this for multiple authors.

To keep this usable and not enforce some development standpoint i would really like to get some suggestions @Brilator @Martin-Kuhl .

**Comment by Freymaurer** [comment]
Some more info about possible solutions: https://docs.ansible.com/ansible/latest/reference_appendices/YAMLSyntax.html

```yaml
# Employee records
- martin:
    name: Martin D'vloper
    job: Developer
    skills:
      - python
      - perl
      - pascal
- tabitha:
    name: Tabitha Bitumen
    job: Developer
    skills:
      - lisp
      - fortran
      - erlang
```
```yaml
martin: {name: Martin D'vloper, job: Developer, skill: Elite}
fruits: ['Apple', 'Orange', 'Strawberry', 'Mango']
```

**Comment by Brilator** [comment]
I was also going to suggest list style, but must be clear how to handle missing values. 

Galaxy training materials have different ways of handling maintainers and contributors (although not always same style). 

See their [contributors yaml](https://github.com/galaxyproject/training-material/blob/main/CONTRIBUTORS.yaml) and different tutorial.mds in [topics](https://github.com/galaxyproject/training-material/tree/main/topics).

**Comment by Brilator** [comment]
The galaxy training materials are overwhelming (hundreds of authors), but they actually have many helpful examples. Also regarding contribution, etc.

**Comment by Brilator** [comment]
> We could see author as maintainer and handle contribution via a special contributer site and GitHub

you mean an overall contributor site similar to that on galaxy?

**Comment by Freymaurer** [comment]
> you mean an overall contributor site similar to that on galaxy?

I have no idea how it looks on galaxy 😅  But i think we mean the same thing

**Comment by Brilator** [comment]
https://training.galaxyproject.org/training-material/

https://training.galaxyproject.org/training-material/hall-of-fame

**Comment by Brilator** [comment]
I mean, let's not overdo to begin with. 
Keep it simple, would this work (sorry, no good at yaml). 

```
authors:
    {
      author: Martin Kuhl
      author_github: martin-kuhl
    }
    {
      author: Dominik Brilhaus
      author_github: brilator
      author_orcid: https://orcid.org/0000-0001-9021-3197
    }
```

**Comment by Martin-Kuhl** [comment]
martin: {name: Martin D'vloper, job: Developer, skill: Elite}
fruits: ['Apple', 'Orange', 'Strawberry', 'Mango']


I like this approach. Looks straightforward and easy to me with all necessary information.

In most cases I guess it will be one main author anyways. And wouldn't git contributions for the articles be sufficient at the moment?

**Comment by Freymaurer** [comment]
From my perspective anything above...
```yml
# only one author possible
author: My Name
author_github: github url
author_orcid: orcid id
```
... requires additional work

If we need multiple authors/maintainers, i could imagine something like this:

```
author: {name: Martin D'vloper, job: Developer, skill: Elite}
author: {name: John Doe, job: Developer, skill: Elite}
author: {name: Jane Doe, job: Developer, skill: Elite}
```

**or**

```yml
authors
  Martin D'vloper: {job: Developer, skill: Elite}
  John Doe: {job: Developer, skill: Elite}
  ...
```

**Comment by Freymaurer** [comment]
We could even allow both cases here:

````yml
# in this case just add name
author: Dominik
# This case for more information
author: {name: Martin D'vloper, job: Developer, skill: Elite}
```
